In [3]:
import pandas as pd
pd.__version__

'2.3.3'

In [11]:
homelessness_df = pd.read_csv("D:\\Jupyter\\Data\\homelessness.csv")
print(homelessness_df.head())
print(homelessness_df.tail(10))
print(type(homelessness_df))

   Unnamed: 0              region       state  individuals  family_members  \
0           0  East South Central     Alabama       2570.0           864.0
1           1             Pacific      Alaska       1434.0           582.0
2           2            Mountain     Arizona       7259.0          2606.0
3           3  West South Central    Arkansas       2280.0           432.0
4           4             Pacific  California     109008.0         20964.0

   state_pop
0    4887681
1     735139
2    7158024
3    3009733
4   39461588
    Unnamed: 0              region          state  individuals  \
41          41  West North Central   South Dakota        836.0
42          42  East South Central      Tennessee       6139.0
43          43  West South Central          Texas      19199.0
44          44            Mountain           Utah       1904.0
45          45         New England        Vermont        780.0
46          46      South Atlantic       Virginia       3928.0
47          47             Pacific     Washington      16424.0
48          48      South Atlantic  West Virginia       1021.0
49          49  East North Central      Wisconsin       2740.0
50          50            Mountain        Wyoming        434.0

    family_members  state_pop
41           323.0     878698
42          1744.0    6771631
43          6111.0   28628666
44           972.0    3153550
45           511.0     624358
46          2047.0    8501286
47          5880.0    7523869
48           222.0    1804291
49          2167.0    5807406
50           205.0     577601
<class 'pandas.core.frame.DataFrame'>

In [14]:
print(homelessness_df.info)

<bound method DataFrame.info of     Unnamed: 0              region                 state  individuals  \
0            0  East South Central               Alabama       2570.0
1            1             Pacific                Alaska       1434.0
2            2            Mountain               Arizona       7259.0
3            3  West South Central              Arkansas       2280.0
4            4             Pacific            California     109008.0
5            5            Mountain              Colorado       7607.0
6            6         New England           Connecticut       2280.0
7            7      South Atlantic              Delaware        708.0
8            8      South Atlantic  District of Columbia       3770.0
9            9      South Atlantic               Florida      21443.0
10          10      South Atlantic               Georgia       6943.0
11          11             Pacific                Hawaii       4131.0
12          12            Mountain                 Idaho       1297.0
13          13  East North Central              Illinois       6752.0
14          14  East North Central               Indiana       3776.0
15          15  West North Central                  Iowa       1711.0
16          16  West North Central                Kansas       1443.0
17          17  East South Central              Kentucky       2735.0
18          18  West South Central             Louisiana       2540.0
19          19         New England                 Maine       1450.0
20          20      South Atlantic              Maryland       4914.0
21          21         New England         Massachusetts       6811.0
22          22  East North Central              Michigan       5209.0
23          23  West North Central             Minnesota       3993.0
24          24  East South Central           Mississippi       1024.0
25          25  West North Central              Missouri       3776.0
26          26            Mountain               Montana        983.0
27          27  West North Central              Nebraska       1745.0
28          28            Mountain                Nevada       7058.0
29          29         New England         New Hampshire        835.0
30          30        Mid-Atlantic            New Jersey       6048.0
31          31            Mountain            New Mexico       1949.0
32          32        Mid-Atlantic              New York      39827.0
33          33      South Atlantic        North Carolina       6451.0
34          34  West North Central          North Dakota        467.0
35          35  East North Central                  Ohio       6929.0
36          36  West South Central              Oklahoma       2823.0
37          37             Pacific                Oregon      11139.0
38          38        Mid-Atlantic          Pennsylvania       8163.0
39          39         New England          Rhode Island        747.0
40          40      South Atlantic        South Carolina       3082.0
41          41  West North Central          South Dakota        836.0
42          42  East South Central             Tennessee       6139.0
43          43  West South Central                 Texas      19199.0
44          44            Mountain                  Utah       1904.0
45          45         New England               Vermont        780.0
46          46      South Atlantic              Virginia       3928.0
47          47             Pacific            Washington      16424.0
48          48      South Atlantic         West Virginia       1021.0
49          49  East North Central             Wisconsin       2740.0
50          50            Mountain               Wyoming        434.0

    family_members  state_pop
0            864.0    4887681
1            582.0     735139
2           2606.0    7158024
3            432.0    3009733
4          20964.0   39461588
5           3250.0    5691287
6           1696.0    3571520
7            374.0     965479
8           3134.0     701547
9           9587.0   21244317
10          2556.0   10511131
11          2399.0    1420593
12           715.0    1750536
13          3891.0   12723071
14          1482.0    6695497
15          1038.0    3148618
16           773.0    2911359
17           953.0    4461153
18           519.0    4659690
19          1066.0    1339057
20          2230.0    6035802
21         13257.0    6882635
22          3142.0    9984072
23          3250.0    5606249
24           328.0    2981020
25          2107.0    6121623
26           422.0    1060665
27           676.0    1925614
28           486.0    3027341
29           615.0    1353465
30          3350.0    8886025
31           602.0    2092741
32         52070.0   19530351
33          2817.0   10381615
34            75.0     758080
35          3320.0   11676341
36          1048.0    3940235
37          3337.0    4181886
38          5349.0   12800922
39           354.0    1058287
40           851.0    5084156
41           323.0     878698
42          1744.0    6771631
43          6111.0   28628666
44           972.0    3153550
45           511.0     624358
46          2047.0    8501286
47          5880.0    7523869
48           222.0    1804291
49          2167.0    5807406
50           205.0     577601  >

In [16]:
homelessness_df.describe()

       Unnamed: 0    individuals  family_members     state_pop
count   51.000000      51.000000       51.000000  5.100000e+01
mean    25.000000    7225.784314     3504.882353  6.405637e+06
std     14.866069   15991.025083     7805.411811  7.327258e+06
min      0.000000     434.000000       75.000000  5.776010e+05
25%     12.500000    1446.500000      592.000000  1.777414e+06
50%     25.000000    3082.000000     1482.000000  4.461153e+06
75%     37.500000    6781.500000     3196.000000  7.340946e+06
max     50.000000  109008.000000    52070.000000  3.946159e+07

In [24]:
 Sales_data = pd.read_excel("D:\\Jupyter\\Data\\sales_data.xlsx")
Sales_data

   Day  Sales Region
0  Mon    200  North
1  Tue    500  South
2  Wed    700   East
3  Thu    100   West
4  Fri    900  North
5  Sat    650  South
6  Sun    300   East

In [21]:
Sales_data.info
Sales_data.columns

Index(['Day', 'Sales', 'Region'], dtype='object')

In [26]:
print(type(Sales_data))
Sales_data.tail()

<class 'pandas.core.frame.DataFrame'>

   Day  Sales Region
2  Wed    700   East
3  Thu    100   West
4  Fri    900  North
5  Sat    650  South
6  Sun    300   East

In [27]:
Sales_data.columns = ["Week Days", "Weekly Sales", "Area"]
Sales_data

  Week Days  Weekly Sales   Area
0       Mon           200  North
1       Tue           500  South
2       Wed           700   East
3       Thu           100   West
4       Fri           900  North
5       Sat           650  South
6       Sun           300   East

In [29]:
Sales_data.to_csv("D:\\Jupyter\\Data\\Modified_Sales_data.csv", index= False)

In [30]:
homelessness_df.columns

Index(['Unnamed: 0', 'region', 'state', 'individuals', 'family_members',
       'state_pop'],
      dtype='object')

Sorting

In [34]:
sorted_homelessness_df = homelessness_df.sort_values(
    by=["family_members"],
    ascending=[True]
)
sorted_homelessness_df.head(10)

,Unnamed: 0,region,state,individuals,family_members,state_pop
34,34,West North Central,North Dakota,467.0,75.0,758080
50,50,Mountain,Wyoming,434.0,205.0,577601
48,48,South Atlantic,West Virginia,1021.0,222.0,1804291
41,41,West North Central,South Dakota,836.0,323.0,878698
24,24,East South Central,Mississippi,1024.0,328.0,2981020
39,39,New England,Rhode Island,747.0,354.0,1058287
7,7,South Atlantic,Delaware,708.0,374.0,965479
26,26,Mountain,Montana,983.0,422.0,1060665
3,3,West South Central,Arkansas,2280.0,432.0,3009733
28,28,Mountain,Nevada,7058.0,486.0,3027341

In [37]:
sorted_homelessness_df = homelessness_df.sort_values(
    by=["region", "family_members"],
    ascending=[True, False]
)
sorted_homelessness_df.head(10)

,Unnamed: 0,region,state,individuals,family_members,state_pop
13,13,East North Central,Illinois,6752.0,3891.0,12723071
35,35,East North Central,Ohio,6929.0,3320.0,11676341
22,22,East North Central,Michigan,5209.0,3142.0,9984072
49,49,East North Central,Wisconsin,2740.0,2167.0,5807406
14,14,East North Central,Indiana,3776.0,1482.0,6695497
42,42,East South Central,Tennessee,6139.0,1744.0,6771631
17,17,East South Central,Kentucky,2735.0,953.0,4461153
0,0,East South Central,Alabama,2570.0,864.0,4887681
24,24,East South Central,Mississippi,1024.0,328.0,2981020
32,32,Mid-Atlantic,New York,39827.0,52070.0,19530351

Feature Engineering

In [39]:
homelessness_df.head()
print(homelessness_df.columns)

Index(['Unnamed: 0', 'region', 'state', 'individuals', 'family_members',
       'state_pop'],
      dtype='object')

In [40]:
New_homelessness_df = homelessness_df[["region", "individuals", "family_members"]]
New_homelessness_df.head()

               region  individuals  family_members
0  East South Central       2570.0           864.0
1             Pacific       1434.0           582.0
2            Mountain       7259.0          2606.0
3  West South Central       2280.0           432.0
4             Pacific     109008.0         20964.0

In [42]:
sorted_new_homelessness_df = New_homelessness_df.sort_values(
    by = ["region", "individuals"],
    ascending=[True, False]
)
sorted_new_homelessness_df.head(10)

                region  individuals  family_members
35  East North Central       6929.0          3320.0
13  East North Central       6752.0          3891.0
22  East North Central       5209.0          3142.0
14  East North Central       3776.0          1482.0
49  East North Central       2740.0          2167.0
42  East South Central       6139.0          1744.0
17  East South Central       2735.0           953.0
0   East South Central       2570.0           864.0
24  East South Central       1024.0           328.0
32        Mid-Atlantic      39827.0         52070.0

Filtering

In [44]:
mask = sorted_new_homelessness_df["region"] == "Mountain"
Filtered_df_mountain = sorted_new_homelessness_df[mask]
print(Filtered_df_mountain)

      region  individuals  family_members
5   Mountain       7607.0          3250.0
2   Mountain       7259.0          2606.0
28  Mountain       7058.0           486.0
31  Mountain       1949.0           602.0
44  Mountain       1904.0           972.0
12  Mountain       1297.0           715.0
26  Mountain        983.0           422.0
50  Mountain        434.0           205.0

In [46]:
homelessness_df_10k = sorted_new_homelessness_df[sorted_homelessness_df["individuals"] > 10000]
homelessness_df_10k.head(10)

C:\Users\LK\AppData\Local\Temp\ipykernel_11640\3896218957.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  homelessness_df_10k = sorted_new_homelessness_df[sorted_homelessness_df["individuals"] > 10000]

                region  individuals  family_members
32        Mid-Atlantic      39827.0         52070.0
4              Pacific     109008.0         20964.0
47             Pacific      16424.0          5880.0
37             Pacific      11139.0          3337.0
9       South Atlantic      21443.0          9587.0
43  West South Central      19199.0          6111.0

In [50]:
family_10k_mask = sorted_homelessness_df["family_members"] < 10000
region_pacific = sorted_homelessness_df["region"] == "Pacific"
New_filtered_df = sorted_homelessness_df[family_10k_mask & region_pacific]
New_filtered_df.head()

    Unnamed: 0   region       state  individuals  family_members  state_pop
47          47  Pacific  Washington      16424.0          5880.0    7523869
37          37  Pacific      Oregon      11139.0          3337.0    4181886
11          11  Pacific      Hawaii       4131.0          2399.0    1420593
1            1  Pacific      Alaska       1434.0           582.0     735139

In [51]:
new_df = sorted_homelessness_df.query(
    "region == 'Pacific' and individuals > 10000"
)
new_df.head()

    Unnamed: 0   region       state  individuals  family_members  state_pop
4            4  Pacific  California     109008.0         20964.0   39461588
47          47  Pacific  Washington      16424.0          5880.0    7523869
37          37  Pacific      Oregon      11139.0          3337.0    4181886

In [53]:
New_df = sorted_homelessness_df.query(
    "state == 'Washington' and individuals > 10000"
)
New_df.head()

    Unnamed: 0   region       state  individuals  family_members  state_pop
47          47  Pacific  Washington      16424.0          5880.0    7523869