In [1]:
import os
import pandas as pd
import numpy as np


root_dir = os.getcwd()
data_dir = os.path.join(root_dir, "Data")
dataset_path = os.path.join(data_dir, "health_monitor_data.csv")

print(root_dir)
print(data_dir)
print(dataset_path)

D:\Jupyter
D:\Jupyter\Data
D:\Jupyter\Data\health_monitor_data.csv

In [2]:
Health_data = pd.read_csv(dataset_path)
Health_data.head()

   Duration          Date  Pulse  Maxpulse  Calories      Type
0        60  '2020/12/01'    110       130     409.1      Easy
1        60  '2020/12/02'    117       145     479.0  Moderate
2        60  '2020/12/03'    103       135     340.0  Moderate
3        45  '2020/12/04'    109       175     282.4  Moderate
4        45  '2020/12/05'    117       148     406.0     Heavy

In [8]:
Health_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33 entries, 0 to 32
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  33 non-null     int64
 1   Date      32 non-null     object
 2   Pulse     33 non-null     int64
 3   Maxpulse  33 non-null     int64
 4   Calories  31 non-null     float64
 5   Type      33 non-null     object
dtypes: float64(1), int64(3), object(2)
memory usage: 1.8+ KB

In [10]:
mask = Health_data.isnull()
print(mask)

    Duration   Date  Pulse  Maxpulse  Calories   Type
0      False  False  False     False     False  False
1      False  False  False     False     False  False
2      False  False  False     False     False  False
3      False  False  False     False     False  False
4      False  False  False     False     False  False
5      False  False  False     False     False  False
6      False  False  False     False     False  False
7      False  False  False     False     False  False
8      False  False  False     False     False  False
9      False  False  False     False     False  False
10     False  False  False     False     False  False
11     False  False  False     False     False  False
12     False  False  False     False     False  False
13     False  False  False     False     False  False
14     False  False  False     False     False  False
15     False  False  False     False     False  False
16     False  False  False     False     False  False
17     False  False  False     False     False  False
18     False  False  False     False      True  False
19     False  False  False     False     False  False
20     False  False  False     False     False  False
21     False  False  False     False     False  False
22     False   True  False     False     False  False
23     False  False  False     False     False  False
24     False  False  False     False     False  False
25     False  False  False     False     False  False
26     False  False  False     False     False  False
27     False  False  False     False     False  False
28     False  False  False     False      True  False
29     False  False  False     False     False  False
30     False  False  False     False     False  False
31     False  False  False     False     False  False
32     False  False  False     False     False  False
Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
Type        0
dtype: int64

In [11]:
print(mask.sum())

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
Type        0
dtype: int64

In [12]:
Health_data.isnull().any()

Duration    False
Date         True
Pulse       False
Maxpulse    False
Calories     True
Type        False
dtype: bool

In [13]:
Health_data.isnull().any(axis= 1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
20    False
21    False
22     True
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
dtype: bool

In [14]:
Health_missing_value_mask = Health_data.isnull().any(axis= 1)
Health_data[Health_missing_value_mask]

    Duration          Date  Pulse  Maxpulse  Calories      Type
18        45  '2020/12/18'     90       112       NaN  Moderate
22        45           NaN    100       119     282.0  Moderate
28        60  '2020/12/28'    103       132       NaN     Heavy

In [21]:
""""Replace empty cells with average values"""
Health_data["Calories"].fillna(
    value= Health_data["Calories"].mean(),
    inplace= True
)

In [18]:
Health_data["Calories"] = Health_data["Calories"].fillna(
    value= Health_data["Calories"].mean()
)
Health_data["Calories"]

0     409.10000
1     479.00000
2     340.00000
3     282.40000
4     406.00000
5     300.00000
6     374.00000
7     253.30000
8     195.10000
9     269.00000
10    329.30000
11    250.70000
12    250.70000
13    345.30000
14    379.30000
15    275.00000
16    215.20000
17    300.00000
18    302.93871
19    323.00000
20    243.00000
21    364.20000
22    282.00000
23    300.00000
24    246.00000
25    334.50000
26    250.00000
27    241.00000
28    302.93871
29    280.00000
30    380.30000
31    243.00000
32    250.70000
Name: Calories, dtype: float64

In [20]:
Health_data.tail()

    Duration          Date  Pulse  Maxpulse   Calories   Type
28        60  '2020/12/28'    103       132  302.93871  Heavy
29        60  '2020/12/29'    100       132  280.00000  Heavy
30        60  '2020/12/30'    102       129  380.30000  Heavy
31        60  '2020/12/31'     92       115  243.00000   Easy
32        60  '2020/12/12'    100       120  250.70000  Heavy

In [22]:
mask2 = Health_data.isnull().any(axis= 1)
Health_data[mask2]

    Duration Date  Pulse  Maxpulse  Calories      Type
22        45  NaN    100       119     282.0  Moderate

In [23]:
Health_data.dropna(inplace= True)

In [24]:
Health_data.isnull().sum()

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
Type        0
dtype: int64

In [3]:
Health_data.head()

   Duration          Date  Pulse  Maxpulse  Calories      Type
0        60  '2020/12/01'    110       130     409.1      Easy
1        60  '2020/12/02'    117       145     479.0  Moderate
2        60  '2020/12/03'    103       135     340.0  Moderate
3        45  '2020/12/04'    109       175     282.4  Moderate
4        45  '2020/12/05'    117       148     406.0     Heavy

In [9]:
Health_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33 entries, 0 to 32
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  33 non-null     int64
 1   Date      32 non-null     object
 2   Pulse     33 non-null     int64
 3   Maxpulse  33 non-null     int64
 4   Calories  31 non-null     float64
 5   Type      33 non-null     object
dtypes: float64(1), int64(3), object(2)
memory usage: 1.8+ KB

In [10]:
Health_data.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
Type        0
dtype: int64

In [13]:
Mask1 = Health_data.isnull().any(axis= 1)
print(Health_data[Mask1])

    Duration          Date  Pulse  Maxpulse  Calories      Type
18        45  '2020/12/18'     90       112       NaN  Moderate
22        45           NaN    100       119     282.0  Moderate
28        60  '2020/12/28'    103       132       NaN     Heavy

In [14]:
Health_data["Calories"].fillna(
    value= Health_data["Calories"].mean(),
    inplace= True
)

In [15]:
print(Health_data[Mask1])

    Duration          Date  Pulse  Maxpulse   Calories      Type
18        45  '2020/12/18'     90       112  302.93871  Moderate
22        45           NaN    100       119  282.00000  Moderate
28        60  '2020/12/28'    103       132  302.93871     Heavy

In [16]:
Health_data.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    0
Type        0
dtype: int64

In [17]:
Health_data.dropna(inplace= True)

In [18]:
Health_data.isnull().sum()

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
Type        0
dtype: int64

In [19]:
Health_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, 0 to 32
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      32 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  32 non-null     float64
 5   Type      32 non-null     object
dtypes: float64(1), int64(3), object(2)
memory usage: 1.8+ KB

In [20]:
Health_data.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32     True
dtype: bool

In [22]:
print(Health_data.duplicated().sum())

1

In [24]:
Duplicated_Health_Data = Health_data.duplicated()
print(Health_data[Duplicated_Health_Data])

    Duration          Date  Pulse  Maxpulse  Calories   Type
32        60  '2020/12/12'    100       120     250.7  Heavy

In [25]:
Health_data.drop_duplicates(inplace= True)

In [27]:
print(Health_data.duplicated().sum())

0

In [28]:
Health_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 0 to 31
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     31 non-null     int64
 3   Maxpulse  31 non-null     int64
 4   Calories  31 non-null     float64
 5   Type      31 non-null     object
dtypes: float64(1), int64(3), object(2)
memory usage: 1.7+ KB

In [30]:
print(Health_data["Date"].dtype)

object

Converting Data Type

In [32]:
Health_data["Date"] = Health_data["Date"].astype("datetime64[ns]")
print(Health_data["Date"].dtype)
print(Health_data.head())

datetime64[ns]
   Duration       Date  Pulse  Maxpulse  Calories      Type
0        60 2020-12-01    110       130     409.1      Easy
1        60 2020-12-02    117       145     479.0  Moderate
2        60 2020-12-03    103       135     340.0  Moderate
3        45 2020-12-04    109       175     282.4  Moderate
4        45 2020-12-05    117       148     406.0     Heavy

In [33]:
Health_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 0 to 31
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      31 non-null     datetime64[ns]
 2   Pulse     31 non-null     int64
 3   Maxpulse  31 non-null     int64
 4   Calories  31 non-null     float64
 5   Type      31 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 1.7+ KB

In [34]:
Health_data.head()

   Duration       Date  Pulse  Maxpulse  Calories      Type
0        60 2020-12-01    110       130     409.1      Easy
1        60 2020-12-02    117       145     479.0  Moderate
2        60 2020-12-03    103       135     340.0  Moderate
3        45 2020-12-04    109       175     282.4  Moderate
4        45 2020-12-05    117       148     406.0     Heavy

Handling Outliers

In [36]:
Q1 = Health_data["Pulse"].quantile(0.25)
print(Q1)
Q3 = Health_data["Pulse"].quantile(0.75)
print(Q3)

IQR = Q3 - Q1
L = Q1 - 1.5 * IQR
R = Q3 + 1.5 * IQR
print(L , R)

100.0
107.0
89.5 117.5

In [37]:
Non_Outlier_data = Health_data["Pulse"].between(L, R)
print(Non_Outlier_data)

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
23    False
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
Name: Pulse, dtype: bool

In [38]:
print(Health_data[~Non_Outlier_data])

    Duration       Date  Pulse  Maxpulse  Calories   Type
23        60 2020-12-23    130       101     300.0  Heavy

In [39]:
Health_data = Health_data[Non_Outlier_data]
Health_data.head()

   Duration       Date  Pulse  Maxpulse  Calories      Type
0        60 2020-12-01    110       130     409.1      Easy
1        60 2020-12-02    117       145     479.0  Moderate
2        60 2020-12-03    103       135     340.0  Moderate
3        45 2020-12-04    109       175     282.4  Moderate
4        45 2020-12-05    117       148     406.0     Heavy

In [40]:
print(Health_data[~Non_Outlier_data])

Empty DataFrame
Columns: [Duration, Date, Pulse, Maxpulse, Calories, Type]
Index: []

C:\Users\LK\AppData\Local\Temp\ipykernel_9608\2745681033.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(Health_data[~Non_Outlier_data])

In [41]:
Health_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 0 to 31
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  30 non-null     int64
 1   Date      30 non-null     datetime64[ns]
 2   Pulse     30 non-null     int64
 3   Maxpulse  30 non-null     int64
 4   Calories  30 non-null     float64
 5   Type      30 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 1.6+ KB