In [1]:
import os
import pandas as pd
import numpy as np

Root_dir = os.getcwd()
Data_dir = os.path.join(Root_dir, "Data")
Dataset_path = os.path.join(Data_dir, "energy_sector_dataset.csv")
print(Root_dir)
print(Data_dir)
print(Dataset_path)

D:\Jupyter
D:\Jupyter\Data
D:\Jupyter\Data\energy_sector_dataset.csv

In [2]:
energy_data = pd.read_csv(Dataset_path)
energy_data.head()

,plant_id,plant_type,country,capacity_mw,generation_mwh,co2_emissions_tons,energy_price_eur_mwh,date
0,202,Hydro,Italy,456.20,1184.53,501.36,110.29,2023-07-20
1,448,Hydro,Germany,181.97,1667.37,1624.55,50.48,2024-08-16
2,370,Coal,Netherlands,6.34,2656.56,1599.52,147.94,2023-12-08
3,206,Wind,France,103.90,4332.21,1467.40,154.12,2024-08-10
4,171,Gas,Italy,484.93,1065.90,1692.48,115.50,2023-10-30

In [3]:
energy_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   plant_id              30000 non-null  int64
 1   plant_type            30000 non-null  object
 2   country               30000 non-null  object
 3   capacity_mw           30000 non-null  float64
 4   generation_mwh        30000 non-null  float64
 5   co2_emissions_tons    30000 non-null  float64
 6   energy_price_eur_mwh  30000 non-null  float64
 7   date                  30000 non-null  object
dtypes: float64(4), int64(1), object(3)
memory usage: 1.8+ MB

In [4]:
energy_data.isnull().sum()

plant_id                0
plant_type              0
country                 0
capacity_mw             0
generation_mwh          0
co2_emissions_tons      0
energy_price_eur_mwh    0
date                    0
dtype: int64

In [7]:
energy_data["date"] = energy_data["date"].astype("datetime64[ns]")
print(energy_data.head())
print(energy_data["date"].dtype)

   plant_id plant_type      country  capacity_mw  generation_mwh  \
0       202      Hydro        Italy       456.20         1184.53
1       448      Hydro      Germany       181.97         1667.37
2       370       Coal  Netherlands         6.34         2656.56
3       206       Wind       France       103.90         4332.21
4       171        Gas        Italy       484.93         1065.90

   co2_emissions_tons  energy_price_eur_mwh       date
0              501.36                110.29 2023-07-20
1             1624.55                 50.48 2024-08-16
2             1599.52                147.94 2023-12-08
3             1467.40                154.12 2024-08-10
4             1692.48                115.50 2023-10-30
datetime64[ns]

In [8]:
Q1 = energy_data["generation_mwh"].quantile(0.25)
print(Q1)
Q3 = energy_data["generation_mwh"].quantile(0.75)
print(Q3)
IQR = Q3 - Q1
L = Q1 - 1.5 * IQR
R = Q3 + 1.5 * IQR
print(L, R)

1273.2
3747.46
-2438.1900000000005 7458.85

In [12]:
Non_outlier_energy_data = energy_data["generation_mwh"].between(L, R)
outliered_energy_data = ~Non_outlier_energy_data
print(energy_data[outliered_energy_data])

Empty DataFrame
Columns: [plant_id, plant_type, country, capacity_mw, generation_mwh, co2_emissions_tons, energy_price_eur_mwh, date]
Index: []

In [13]:
energy_data = energy_data[Non_outlier_energy_data]
energy_data.head()

,plant_id,plant_type,country,capacity_mw,generation_mwh,co2_emissions_tons,energy_price_eur_mwh,date
0,202,Hydro,Italy,456.20,1184.53,501.36,110.29,2023-07-20
1,448,Hydro,Germany,181.97,1667.37,1624.55,50.48,2024-08-16
2,370,Coal,Netherlands,6.34,2656.56,1599.52,147.94,2023-12-08
3,206,Wind,France,103.90,4332.21,1467.40,154.12,2024-08-10
4,171,Gas,Italy,484.93,1065.90,1692.48,115.50,2023-10-30

In [14]:
print(energy_data[outliered_energy_data])

Empty DataFrame
Columns: [plant_id, plant_type, country, capacity_mw, generation_mwh, co2_emissions_tons, energy_price_eur_mwh, date]
Index: []

In [15]:
energy_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   plant_id              30000 non-null  int64
 1   plant_type            30000 non-null  object
 2   country               30000 non-null  object
 3   capacity_mw           30000 non-null  float64
 4   generation_mwh        30000 non-null  float64
 5   co2_emissions_tons    30000 non-null  float64
 6   energy_price_eur_mwh  30000 non-null  float64
 7   date                  30000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(4), int64(1), object(2)
memory usage: 1.8+ MB

In [16]:
energy_data.duplicated().sum()

np.int64(0)

In [19]:
energy_data.head()

,plant_id,plant_type,country,capacity_mw,generation_mwh,co2_emissions_tons,energy_price_eur_mwh,date
0,202,Hydro,Italy,456.20,1184.53,501.36,110.29,2023-07-20
1,448,Hydro,Germany,181.97,1667.37,1624.55,50.48,2024-08-16
2,370,Coal,Netherlands,6.34,2656.56,1599.52,147.94,2023-12-08
3,206,Wind,France,103.90,4332.21,1467.40,154.12,2024-08-10
4,171,Gas,Italy,484.93,1065.90,1692.48,115.50,2023-10-30

In [22]:
def normalization(col):
    Mean = col.mean()
    Std = col.std()
    return (col - Mean) / Std
energy_data["generation_mwh"] = energy_data["generation_mwh"].agg(normalization)
energy_data["capacity_mw"] = energy_data["capacity_mw"].agg(normalization)
energy_data["co2_emissions_tons"] = energy_data["co2_emissions_tons"].agg(normalization)
energy_data["energy_price_eur_mwh"] = energy_data["energy_price_eur_mwh"].agg(normalization)
energy_data.head()

,plant_id,plant_type,country,capacity_mw,generation_mwh,co2_emissions_tons,energy_price_eur_mwh,date
0,202,Hydro,Italy,1.425506,-0.932019,-0.874626,0.002002,2023-07-20
1,448,Hydro,Germany,-0.493319,-0.593894,1.067244,-1.151644,2024-08-16
2,370,Coal,Netherlands,-1.722226,0.098820,1.023970,0.728215,2023-12-08
3,206,Wind,France,-1.039585,1.272251,0.795549,0.847418,2024-08-10
4,171,Gas,Italy,1.626534,-1.015094,1.184687,0.102496,2023-10-30

In [25]:
energy_data = energy_data.drop(columns=["plant_id"])
energy_data.head()

,plant_type,country,capacity_mw,generation_mwh,co2_emissions_tons,energy_price_eur_mwh,date
0,Hydro,Italy,1.425506,-0.932019,-0.874626,0.002002,2023-07-20
1,Hydro,Germany,-0.493319,-0.593894,1.067244,-1.151644,2024-08-16
2,Coal,Netherlands,-1.722226,0.098820,1.023970,0.728215,2023-12-08
3,Wind,France,-1.039585,1.272251,0.795549,0.847418,2024-08-10
4,Gas,Italy,1.626534,-1.015094,1.184687,0.102496,2023-10-30

In [30]:
sorted_energy_data = energy_data.sort_values(
    by = ["plant_type"],
    ascending= True
)
sorted_energy_data.head(10)

,plant_type,country,capacity_mw,generation_mwh,co2_emissions_tons,energy_price_eur_mwh,date
14999,Coal,France,1.026110,-0.630540,-1.254307,0.024377,2023-07-12
13179,Coal,Germany,-1.321080,1.198911,1.462744,0.479586,2023-06-15
13180,Coal,France,-1.227039,-1.352841,1.323465,1.086210,2023-07-16
13181,Coal,Netherlands,-1.451227,0.430139,-1.478648,-0.982677,2024-08-26
13184,Coal,Italy,-0.595897,-0.082567,1.330450,-0.092704,2023-10-23
13189,Coal,France,-0.054108,0.769433,-0.288619,0.365398,2023-04-16
13195,Coal,Germany,1.235744,-0.290110,0.381031,-0.542705,2024-08-27
13204,Coal,Germany,1.635421,-0.144830,0.594912,1.001919,2023-09-14
13206,Coal,Germany,1.162414,0.219885,1.373119,1.560129,2023-12-08
13214,Coal,Netherlands,-0.468759,-0.929337,-0.229336,0.470135,2023-05-09

In [31]:
mask4 = energy_data["plant_type"] == "Wind"
Wind_energy_data = energy_data[mask4]
Wind_energy_data

,plant_type,country,capacity_mw,generation_mwh,co2_emissions_tons,energy_price_eur_mwh,date
3,Wind,France,-1.039585,1.272251,0.795549,0.847418,2024-08-10
17,Wind,Netherlands,0.266500,-1.527547,0.619548,-0.464780,2023-12-02
24,Wind,Spain,0.778831,-0.971172,-0.863855,1.240325,2023-07-08
28,Wind,Germany,-1.377407,-1.164485,1.353271,1.163364,2023-12-12
30,Wind,Netherlands,-1.144752,-1.688473,-1.697975,0.838353,2023-05-26
...,...,...,...,...,...,...,...
29964,Wind,Netherlands,0.641407,0.297841,0.566316,0.201639,2024-12-09
29965,Wind,Netherlands,-1.354666,0.995310,-0.940825,-0.956637,2023-03-14
29976,Wind,Spain,-1.602225,-1.310655,-0.181480,0.664563,2023-01-17
29986,Wind,Italy,-0.095182,-0.786402,-1.400156,-0.240840,2023-03-25
29989,Wind,France,1.173260,-1.133295,-0.982128,-1.367290,2024-02-02

In [34]:
Coal_energy_data = energy_data.query(
    "plant_type == 'Coal' and country == 'France'"
)
Coal_energy_data

,plant_type,country,capacity_mw,generation_mwh,co2_emissions_tons,energy_price_eur_mwh,date
48,Coal,France,-0.719536,-1.633549,0.148703,0.746539,2023-12-18
72,Coal,France,-1.536732,0.469901,0.241112,0.086293,2024-03-27
97,Coal,France,-1.005369,-1.108988,-1.662774,-1.534328,2023-10-11
136,Coal,France,0.530572,0.906906,-1.353546,-0.650721,2024-08-23
156,Coal,France,-1.326818,1.649676,-0.473438,-1.285699,2023-04-04
...,...,...,...,...,...,...,...
29865,Coal,France,1.125469,-1.289745,-1.310738,0.058518,2024-01-28
29872,Coal,France,0.572625,-0.776360,0.837509,0.849347,2023-11-15
29906,Coal,France,-0.510392,0.067763,-0.361146,0.623671,2024-12-18
29991,Coal,France,-1.661491,1.519571,1.576108,-0.942942,2024-08-23
29999,Coal,France,1.034926,-0.184003,-0.584190,-0.676761,2024-11-30