In [1]:
import os
import pandas as pd
import numpy as np

root_dir = os.getcwd()
data_dir = os.path.join(root_dir, "Data")
dataset_path = os.path.join(data_dir, "sales_subset.csv")

print("root dir: ", root_dir)
print("data dir: ", data_dir)
print("dataset path: ", dataset_path)

root dir:  D:\Jupyter
data dir:  D:\Jupyter\Data
dataset path:  D:\Jupyter\Data\sales_subset.csv

In [2]:
sales_data = pd.read_csv(dataset_path)
sales_data.head()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,1,1,A,1,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,2,1,A,1,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,3,1,A,1,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,4,1,A,1,2010-06-04,17558.09,False,27.050000,0.714586,7.808

In [3]:
sales_data.columns

Index(['Unnamed: 0', 'store', 'type', 'department', 'date', 'weekly_sales',
       'is_holiday', 'temperature_c', 'fuel_price_usd_per_l', 'unemployment'],
      dtype='object')

In [10]:
sales_data = sales_data.drop(columns = ["department"])
sales_data.head()

,store,type,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,1,A,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,1,A,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,1,A,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,1,A,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,1,A,2010-06-04,17558.09,False,27.050000,0.714586,7.808

In [11]:
sales_data.columns = ["Store", "Type", "Date", "Weekly Sales", "Holiday or NOt", "Temperature", "Fuel Price USD", "Unemployment"]
sales_data.head()

,Store,Type,Date,Weekly Sales,Holiday or NOt,Temperature,Fuel Price USD,Unemployment
0,1,A,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,1,A,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,1,A,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,1,A,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,1,A,2010-06-04,17558.09,False,27.050000,0.714586,7.808

In [12]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10774 entries, 0 to 10773
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Store           10774 non-null  int64
 1   Type            10774 non-null  object
 2   Date            10774 non-null  object
 3   Weekly Sales    10774 non-null  float64
 4   Holiday or NOt  10774 non-null  bool
 5   Temperature     10774 non-null  float64
 6   Fuel Price USD  10774 non-null  float64
 7   Unemployment    10774 non-null  float64
dtypes: bool(1), float64(4), int64(1), object(2)
memory usage: 599.9+ KB

In [15]:
Avarage_weekly_sales = sales_data[["Weekly Sales", "Fuel Price USD"]].mean()
print(Avarage_weekly_sales)

Weekly Sales      23843.950149
Fuel Price USD        0.749746
dtype: float64

In [20]:
average_weekly_sales = np.mean(sales_data[["Weekly Sales"]])
print(average_weekly_sales)

23843.95014850566

In [22]:
print("mean: ", sales_data["Weekly Sales"].mean())
print("median: ", sales_data["Weekly Sales"].median())
print("Max: ", sales_data["Date"].max())
print("Min: ", sales_data["Date"].min())
print("sum: ", sales_data["Weekly Sales"].sum())

mean:  23843.95014850566
median:  12049.064999999999
Max:  2012-10-26
Min:  2010-02-05
sum:  256894718.89999998

In [25]:
print(sales_data["Weekly Sales"].cumsum())

0        2.492450e+04
1        4.675240e+04
2        1.040108e+05
3        1.214248e+05
4        1.389829e+05
             ...
10769    2.568930e+08
10770    2.568934e+08
10771    2.568938e+08
10772    2.568938e+08
10773    2.568947e+08
Name: Weekly Sales, Length: 10774, dtype: float64

In [26]:
sales_data["Weekly Sales"].cummax()

0         24924.50
1         24924.50
2         57258.43
3         57258.43
4         57258.43
           ...
10769    293966.05
10770    293966.05
10771    293966.05
10772    293966.05
10773    293966.05
Name: Weekly Sales, Length: 10774, dtype: float64

In [27]:
sales_data["Weekly Sales"].cummin()

0        24924.50
1        21827.90
2        21827.90
3        17413.94
4        17413.94
           ...
10769    -1098.00
10770    -1098.00
10771    -1098.00
10772    -1098.00
10773    -1098.00
Name: Weekly Sales, Length: 10774, dtype: float64

Custom Method for Normalization or Standardization

In [28]:
sales_data.head()

,Store,Type,Date,Weekly Sales,Holiday or NOt,Temperature,Fuel Price USD,Unemployment
0,1,A,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,1,A,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,1,A,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,1,A,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,1,A,2010-06-04,17558.09,False,27.050000,0.714586,7.808

In [30]:
def standardization(col):
    Mean = col.mean()
    Std = col.std()
    return (col - Mean) / Std
Normalized_Weekly_Sales_and_Temp = sales_data[["Weekly Sales", "Temperature"]].agg([standardization, np.cumsum])
Normalized_Weekly_Sales_and_Temp.head()

C:\Users\LK\AppData\Local\Temp\ipykernel_14456\4242884880.py:5: FutureWarning: The provided callable <function cumsum at 0x00000218A26B4300> is currently using Series.cumsum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "cumsum" instead.
  Normalized_Weekly_Sales_and_Temp = sales_data[["Weekly Sales", "Temperature"]].agg([standardization, np.cumsum])

     Weekly Sales                Temperature
  standardization     cumsum standardization     cumsum
0        0.035756   24924.50       -1.008239   5.727778
1       -0.066712   46752.40       -0.773642  13.783333
2        1.105693  104010.83        0.109317  30.600000
3       -0.212771  121424.77        0.684892  53.127778
4       -0.208001  138982.86        1.140648  80.177778

In [31]:
Normalized_Weekly_Sales_and_Temp.max(), Normalized_Weekly_Sales_and_Temp.min()

(Weekly Sales  standardization    8.938406e+00
               cumsum             2.568947e+08
 Temperature   standardization    1.823724e+00
               cumsum             1.694963e+05
 dtype: float64,
 Weekly Sales  standardization       -0.825335
               cumsum             24924.500000
 Temperature   standardization       -2.428700
               cumsum                 5.727778
 dtype: float64)

Pandas Methods for Catagorical Data

In [32]:
sales_data["Type"].value_counts()

Type
A    9872
B     902
Name: count, dtype: int64

In [36]:
sales_data["Store"].value_counts(
    ascending= True
)

Store
39    875
14    885
31    890
6     894
2     897
27    900
4     901
1     901
10    902
19    906
20    910
13    913
Name: count, dtype: int64

In [37]:
"""Group By"""
Sales_grouped_data = sales_data.groupby("Type")
Sales_grouped_data.head(10)

,Store,Type,Date,Weekly Sales,Holiday or NOt,Temperature,Fuel Price USD,Unemployment
0,1,A,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,1,A,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,1,A,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,1,A,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,1,A,2010-06-04,17558.09,False,27.050000,0.714586,7.808
5,1,A,2010-07-02,16333.14,False,27.172222,0.705076,7.787
6,1,A,2010-08-06,17508.41,False,30.644444,0.693980,7.787
7,1,A,2010-09-03,16241.78,False,27.338889,0.680772,7.787
8,1,A,2010-10-01,20094.19,False,22.161111,0.687640,7.838
9,1,A,2010-11-05,34238.88,False,14.855556,0.710359,7.838
3593,10,B,2010-02-05,40212.84,False,12.411111,0.782478,9.765
3594,10,B,2010-03-05,36572.44,False,13.288889,0.760023,9.765
3595,10,B,2010-04-02,131853.01,False,17.588889,0.815235,9.524
3596,10,B,2010-05-07,29819.93,False,21.700000,0.826066,9.524
3597,10,B,2010-06-04,27739.80,False,28.233333,0.776930,9.524
3598,10,B,2010-07-02,27233.92,False,33.827778,0.786705,9.199
3599,10,B,2010-08-06,26778.10,False,30.072222,0.825010,9.199
3600,10,B,2010-09-03,29253.15,False,28.777778,0.815500,9.199
3601,10,B,2010-10-01,34152.79,False,30.005556,0.792781,9.003
3602,10,B,2010-11-05,68006.65,False,21.688889,0.794894,9.003

In [39]:
Sales_grouped_data["Weekly Sales"].sum()

Type
A    2.337163e+08
B    2.317840e+07
Name: Weekly Sales, dtype: float64

In [40]:
Sales_statistics = sales_data.groupby("Type")["Weekly Sales"].agg([min, max, np.mean, np.median])
Sales_statistics.head()

C:\Users\LK\AppData\Local\Temp\ipykernel_14456\2633980324.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  Sales_statistics = sales_data.groupby("Type")["Weekly Sales"].agg([min, max, np.mean, np.median])
C:\Users\LK\AppData\Local\Temp\ipykernel_14456\2633980324.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  Sales_statistics = sales_data.groupby("Type")["Weekly Sales"].agg([min, max, np.mean, np.median])
C:\Users\LK\AppData\Local\Temp\ipykernel_14456\2633980324.py:1: FutureWarning: The provided callable <function mean at 0x00000218A26B5170> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  Sales_statistics = sales_data.groupby("Type")["Weekly Sales"].agg([min, max, np.mean, np.median])
C:\Users\LK\AppData\Local\Temp\ipykernel_14456\2633980324.py:1: FutureWarning: The provided callable <function median at 0x00000218A27DB320> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  Sales_statistics = sales_data.groupby("Type")["Weekly Sales"].agg([min, max, np.mean, np.median])

         min        max          mean    median
Type
A    -1098.0  293966.05  23674.667242  11943.92
B     -798.0  232558.51  25696.678370  13336.08

In [41]:
sales_data.head()

,Store,Type,Date,Weekly Sales,Holiday or NOt,Temperature,Fuel Price USD,Unemployment
0,1,A,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,1,A,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,1,A,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,1,A,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,1,A,2010-06-04,17558.09,False,27.050000,0.714586,7.808

In [42]:
Sales_row = sales_data.iloc[0, :]
print(Sales_row)

Store                      1
Type                       A
Date              2010-02-05
Weekly Sales         24924.5
Holiday or NOt         False
Temperature         5.727778
Fuel Price USD      0.679451
Unemployment           8.106
Name: 0, dtype: object

In [43]:
Sales_rows = sales_data.iloc[0:6, 3:6]
print(Sales_rows)

   Weekly Sales  Holiday or NOt  Temperature
0      24924.50           False     5.727778
1      21827.90           False     8.055556
2      57258.43           False    16.816667
3      17413.94           False    22.527778
4      17558.09           False    27.050000
5      16333.14           False    27.172222

In [44]:
""" Pivot Table"""
Sales_Pivot = sales_data.pivot_table(
    index= "Type",
    values= "Weekly Sales",
    aggfunc=[min, max, np.mean, np.median]
)
Sales_Pivot

C:\Users\LK\AppData\Local\Temp\ipykernel_14456\2170540928.py:2: FutureWarning: The provided callable <built-in function min> is currently using DataFrameGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  Sales_Pivot = sales_data.pivot_table(
C:\Users\LK\AppData\Local\Temp\ipykernel_14456\2170540928.py:2: FutureWarning: The provided callable <built-in function max> is currently using DataFrameGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  Sales_Pivot = sales_data.pivot_table(
C:\Users\LK\AppData\Local\Temp\ipykernel_14456\2170540928.py:2: FutureWarning: The provided callable <function mean at 0x00000218A26B5170> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  Sales_Pivot = sales_data.pivot_table(
C:\Users\LK\AppData\Local\Temp\ipykernel_14456\2170540928.py:2: FutureWarning: The provided callable <function median at 0x00000218A27DB320> is currently using DataFrameGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  Sales_Pivot = sales_data.pivot_table(

              min          max          mean       median
     Weekly Sales Weekly Sales  Weekly Sales Weekly Sales
Type
A         -1098.0    293966.05  23674.667242     11943.92
B          -798.0    232558.51  25696.678370     13336.08

In [45]:
Sales_pivot = sales_data.pivot_table(
    index= "Type",
    values= "Weekly Sales",
    columns= "Holiday or NOt",
    aggfunc= [np.mean]
)
Sales_pivot

C:\Users\LK\AppData\Local\Temp\ipykernel_14456\2936467825.py:1: FutureWarning: The provided callable <function mean at 0x00000218A26B5170> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  Sales_pivot = sales_data.pivot_table(

                        mean
Holiday or NOt         False      True
Type
A               23768.583523  590.04525
B               25751.980533  810.70500