In [1]:
import pandas as pd
import os

from pandas.core.array_algos.masked_accumulations import cummax

root_dir = os.getcwd()
data_dir = os.path.join(root_dir, "Data")
dataset_path = os.path.join(data_dir, "sales_subset.csv")

print("root directory: ", root_dir)
print("dataset directory: ", data_dir)
print("dataset path: ", dataset_path)

root directory:  D:\Jupyter
dataset directory:  D:\Jupyter\Data
dataset path:  D:\Jupyter\Data\sales_subset.csv

In [2]:
os.getcwd()

'D:\\Jupyter'

In [3]:
Sales = pd.read_csv(dataset_path)
Sales.head()

,Unnamed: 0,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,1,1,A,1,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,2,1,A,1,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,3,1,A,1,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,4,1,A,1,2010-06-04,17558.09,False,27.050000,0.714586,7.808

In [4]:
Sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10774 entries, 0 to 10773
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            10774 non-null  int64
 1   store                 10774 non-null  int64
 2   type                  10774 non-null  object
 3   department            10774 non-null  int64
 4   date                  10774 non-null  object
 5   weekly_sales          10774 non-null  float64
 6   is_holiday            10774 non-null  bool
 7   temperature_c         10774 non-null  float64
 8   fuel_price_usd_per_l  10774 non-null  float64
 9   unemployment          10774 non-null  float64
dtypes: bool(1), float64(4), int64(3), object(2)
memory usage: 768.2+ KB

In [5]:
Sales = Sales.drop(columns= ["Unnamed: 0", "store", "department"])
Sales.head()

,type,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,A,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,A,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,A,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,A,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,A,2010-06-04,17558.09,False,27.050000,0.714586,7.808

In [6]:
mask = Sales["weekly_sales"] < 20000
Sales_less_20000 = Sales[mask]
Sales_less_20000

,type,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
3,A,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,A,2010-06-04,17558.09,False,27.050000,0.714586,7.808
5,A,2010-07-02,16333.14,False,27.172222,0.705076,7.787
6,A,2010-08-06,17508.41,False,30.644444,0.693980,7.787
7,A,2010-09-03,16241.78,False,27.338889,0.680772,7.787
...,...,...,...,...,...,...,...
10769,A,2011-12-09,895.00,False,9.644444,0.834256,7.716
10770,A,2012-02-03,350.00,False,15.938889,0.887619,7.244
10771,A,2012-06-08,450.00,False,27.288889,0.911922,6.989
10772,A,2012-07-13,0.06,False,25.644444,0.860145,6.623
10773,A,2012-10-05,915.00,False,22.250000,0.955511,6.228

In [7]:
sales_weeklysale_more_20000 = Sales.query(
    "weekly_sales > 20000 and unemployment > 7"
)
sales_weeklysale_more_20000

,type,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,A,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,A,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,A,2010-04-02,57258.43,False,16.816667,0.718284,7.808
8,A,2010-10-01,20094.19,False,22.161111,0.687640,7.838
9,A,2010-11-05,34238.88,False,14.855556,0.710359,7.838
...,...,...,...,...,...,...,...
10746,A,2010-09-03,26882.38,False,27.850000,0.680772,8.360
10747,A,2010-10-01,22813.33,False,22.633333,0.687640,8.476
10748,A,2010-11-05,24082.80,False,16.455556,0.710359,8.476
10749,A,2010-12-03,21444.94,False,11.972222,0.715378,8.476
10750,A,2011-01-07,22660.01,False,11.522222,0.786176,8.395

In [8]:
Sales.columns

Index(['type', 'date', 'weekly_sales', 'is_holiday', 'temperature_c',
       'fuel_price_usd_per_l', 'unemployment'],
      dtype='object')

In [9]:
Sales.columns = ["Type", "Date", "Weekly Sales", "Holiday", "Temperature C", "Fuel Price", "Unemployment"]
Sales.head()

,Type,Date,Weekly Sales,Holiday,Temperature C,Fuel Price,Unemployment
0,A,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,A,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,A,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,A,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,A,2010-06-04,17558.09,False,27.050000,0.714586,7.808

In [10]:
Sales.tail()

,Type,Date,Weekly Sales,Holiday,Temperature C,Fuel Price,Unemployment
10769,A,2011-12-09,895.00,False,9.644444,0.834256,7.716
10770,A,2012-02-03,350.00,False,15.938889,0.887619,7.244
10771,A,2012-06-08,450.00,False,27.288889,0.911922,6.989
10772,A,2012-07-13,0.06,False,25.644444,0.860145,6.623
10773,A,2012-10-05,915.00,False,22.250000,0.955511,6.228

In [11]:
Avarage_weekly_sales = Sales["Weekly Sales"].mean()
print(Avarage_weekly_sales)

23843.95014850566

In [12]:
import numpy as np
Avarage_weekly = np.mean(Sales["Weekly Sales"])
print(Avarage_weekly)

23843.95014850566

In [13]:
Sales[["Weekly Sales", "Fuel Price"]].mean()

Weekly Sales    23843.950149
Fuel Price          0.749746
dtype: float64

In [14]:
Sales["Weekly Sales"].cumsum()

0        2.492450e+04
1        4.675240e+04
2        1.040108e+05
3        1.214248e+05
4        1.389829e+05
             ...
10769    2.568930e+08
10770    2.568934e+08
10771    2.568938e+08
10772    2.568938e+08
10773    2.568947e+08
Name: Weekly Sales, Length: 10774, dtype: float64

In [15]:
Sales["Weekly Sales"].cummax()

0         24924.50
1         24924.50
2         57258.43
3         57258.43
4         57258.43
           ...
10769    293966.05
10770    293966.05
10771    293966.05
10772    293966.05
10773    293966.05
Name: Weekly Sales, Length: 10774, dtype: float64

In [16]:
Sales["Weekly Sales"].cummin()

0        24924.50
1        21827.90
2        21827.90
3        17413.94
4        17413.94
           ...
10769    -1098.00
10770    -1098.00
10771    -1098.00
10772    -1098.00
10773    -1098.00
Name: Weekly Sales, Length: 10774, dtype: float64

In [17]:
Sales.head()

,Type,Date,Weekly Sales,Holiday,Temperature C,Fuel Price,Unemployment
0,A,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,A,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,A,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,A,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,A,2010-06-04,17558.09,False,27.050000,0.714586,7.808

Normalisation or standardization

In [27]:
def normalize(col):
    mean = col.mean()
    std = col.std()
    return (col - mean) / std
normalized_sales_temp = Sales[["Weekly Sales", "Temperature C"]].agg([normalize, np.cumsum])
normalized_sales_temp

C:\Users\LK\AppData\Local\Temp\ipykernel_19656\1971351837.py:5: FutureWarning: The provided callable <function cumsum at 0x00000200584840F0> is currently using Series.cumsum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "cumsum" instead.
  normalized_sales_temp = Sales[["Weekly Sales", "Temperature C"]].agg([normalize, np.cumsum])

      Weekly Sales               Temperature C
         normalize        cumsum     normalize         cumsum
0         0.035756  2.492450e+04     -1.008239       5.727778
1        -0.066712  4.675240e+04     -0.773642      13.783333
2         1.105693  1.040108e+05      0.109317      30.600000
3        -0.212771  1.214248e+05      0.684892      53.127778
4        -0.208001  1.389829e+05      1.140648      80.177778
...            ...           ...           ...            ...
10769    -0.759386  2.568930e+08     -0.613511  169405.211111
10770    -0.777421  2.568934e+08      0.020853  169421.150000
10771    -0.774112  2.568938e+08      1.164724  169448.438889
10772    -0.789000  2.568938e+08      0.998994  169474.083333
10773    -0.758725  2.568947e+08      0.656897  169496.333333

[10774 rows x 4 columns]

In [29]:
"""Pandas methods for catagorical data"""
Sales[["Type"]].value_counts()

Type
A       9872
B        902
Name: count, dtype: int64

In [32]:
"""Group By"""
Sales_groupby_type = Sales.groupby("Type")
Sales_groupby_type.head()

,Type,Date,Weekly Sales,Holiday,Temperature C,Fuel Price,Unemployment
0,A,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,A,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,A,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,A,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,A,2010-06-04,17558.09,False,27.050000,0.714586,7.808
3593,B,2010-02-05,40212.84,False,12.411111,0.782478,9.765
3594,B,2010-03-05,36572.44,False,13.288889,0.760023,9.765
3595,B,2010-04-02,131853.01,False,17.588889,0.815235,9.524
3596,B,2010-05-07,29819.93,False,21.700000,0.826066,9.524
3597,B,2010-06-04,27739.80,False,28.233333,0.776930,9.524

In [34]:
Sales_groupby_type["Weekly Sales"].mean()

Type
A    23674.667242
B    25696.678370
Name: Weekly Sales, dtype: float64

In [38]:
sales_stats = Sales.groupby("Type")["Weekly Sales"].agg([max, min, np.mean, np.median])
sales_stats

C:\Users\LK\AppData\Local\Temp\ipykernel_19656\655861528.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  sales_stats = Sales.groupby("Type")["Weekly Sales"].agg([max, min, np.mean, np.median])
C:\Users\LK\AppData\Local\Temp\ipykernel_19656\655861528.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  sales_stats = Sales.groupby("Type")["Weekly Sales"].agg([max, min, np.mean, np.median])
C:\Users\LK\AppData\Local\Temp\ipykernel_19656\655861528.py:1: FutureWarning: The provided callable <function mean at 0x0000020058484F60> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  sales_stats = Sales.groupby("Type")["Weekly Sales"].agg([max, min, np.mean, np.median])
C:\Users\LK\AppData\Local\Temp\ipykernel_19656\655861528.py:1: FutureWarning: The provided callable <function median at 0x00000200585AB110> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  sales_stats = Sales.groupby("Type")["Weekly Sales"].agg([max, min, np.mean, np.median])

            max     min          mean    median
Type
A     293966.05 -1098.0  23674.667242  11943.92
B     232558.51  -798.0  25696.678370  13336.08

In [39]:
rows = Sales.iloc[1, :]
rows

Type                      A
Date             2010-03-05
Weekly Sales        21827.9
Holiday               False
Temperature C      8.055556
Fuel Price         0.693452
Unemployment          8.106
Name: 1, dtype: object

In [40]:
mean_sales_by_type = Sales.pivot_table(
    values= ["Weekly Sales"],
    index= "Type",
    aggfunc= [min, max, np.mean, np.median]
)
mean_sales_by_type

C:\Users\LK\AppData\Local\Temp\ipykernel_19656\4088763941.py:1: FutureWarning: The provided callable <built-in function min> is currently using DataFrameGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  mean_sales_by_type = Sales.pivot_table(
C:\Users\LK\AppData\Local\Temp\ipykernel_19656\4088763941.py:1: FutureWarning: The provided callable <built-in function max> is currently using DataFrameGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  mean_sales_by_type = Sales.pivot_table(
C:\Users\LK\AppData\Local\Temp\ipykernel_19656\4088763941.py:1: FutureWarning: The provided callable <function mean at 0x0000020058484F60> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  mean_sales_by_type = Sales.pivot_table(
C:\Users\LK\AppData\Local\Temp\ipykernel_19656\4088763941.py:1: FutureWarning: The provided callable <function median at 0x00000200585AB110> is currently using DataFrameGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  mean_sales_by_type = Sales.pivot_table(

              min          max          mean       median
     Weekly Sales Weekly Sales  Weekly Sales Weekly Sales
Type
A         -1098.0    293966.05  23674.667242     11943.92
B          -798.0    232558.51  25696.678370     13336.08

In [41]:
mean_sales_by_type1 = Sales.pivot_table(
    values= ['Weekly Sales'],
    index= "Type",
    columns= ["Holiday"],
    aggfunc= [min, max, np.mean, np.median]
)
mean_sales_by_type1

C:\Users\LK\AppData\Local\Temp\ipykernel_19656\116047304.py:1: FutureWarning: The provided callable <built-in function min> is currently using DataFrameGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  mean_sales_by_type1 = Sales.pivot_table(
C:\Users\LK\AppData\Local\Temp\ipykernel_19656\116047304.py:1: FutureWarning: The provided callable <built-in function max> is currently using DataFrameGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  mean_sales_by_type1 = Sales.pivot_table(
C:\Users\LK\AppData\Local\Temp\ipykernel_19656\116047304.py:1: FutureWarning: The provided callable <function mean at 0x0000020058484F60> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  mean_sales_by_type1 = Sales.pivot_table(
C:\Users\LK\AppData\Local\Temp\ipykernel_19656\116047304.py:1: FutureWarning: The provided callable <function median at 0x00000200585AB110> is currently using DataFrameGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  mean_sales_by_type1 = Sales.pivot_table(

                 min                  max                  mean             \
        Weekly Sales         Weekly Sales          Weekly Sales
Holiday        False   True         False   True          False      True
Type
A            -1098.0 -598.00    293966.05  5350.0  23768.583523  590.04525
B             -798.0   31.41    232558.51  1590.0  25751.980533  810.70500

              median
        Weekly Sales
Holiday        False    True
Type
A          12028.955   37.500
B          13348.680  810.705

In [42]:
Sales.head()

,Type,Date,Weekly Sales,Holiday,Temperature C,Fuel Price,Unemployment
0,A,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,A,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,A,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,A,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,A,2010-06-04,17558.09,False,27.050000,0.714586,7.808

In [44]:
def standardization(col):
    Mean = col.mean()
    Std = col.std()
    return (col - Mean) / Std
Standardized_weekly_sales_and_temp = Sales[["Weekly Sales", "Temperature C"]].agg([standardization])
Standardized_weekly_sales_and_temp.head()

     Weekly Sales   Temperature C
  standardization standardization
0        0.035756       -1.008239
1       -0.066712       -0.773642
2        1.105693        0.109317
3       -0.212771        0.684892
4       -0.208001        1.140648