In [4]:
import pandas as pd

from Data_Science_Pandas_Dataframe import New_homelessness_df, sorted_new_homelessness_df

Health_data_table = {
    "Height": [5.5, 5.7, 6.0, 5.3, 5.6],
    "Weight": [57, 60, 84, 74, 61],
    "bmi": [20.1, 17.2, 18.0, 17.9, 19.0]
}
Health_data_frame = pd.DataFrame(Health_data_table)
print(Health_data_frame)
print(type(Health_data_frame))

   Height  Weight   bmi
0     5.5      57  20.1
1     5.7      60  17.2
2     6.0      84  18.0
3     5.3      74  17.9
4     5.6      61  19.0
<class 'pandas.core.frame.DataFrame'>

In [6]:
Health_data_frame.head()
Health_data_frame.tail()

   Height  Weight   bmi
0     5.5      57  20.1
1     5.7      60  17.2
2     6.0      84  18.0
3     5.3      74  17.9
4     5.6      61  19.0

In [7]:
Health_data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Height  5 non-null      float64
 1   Weight  5 non-null      int64
 2   bmi     5 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 252.0 bytes

In [13]:
Health_data_frame.describe()
Health_data_frame.values
print(Health_data_frame.columns)
Health_data_frame.to_csv("D:\\Jupyter\\Data\\Health_data.csv",
                         index= False)

Index(['Height', 'Weight', 'bmi'], dtype='object')

In [16]:
Homelessness_data = pd.read_csv("D:\\Jupyter\\Data\\homelessness.csv")
# Homelessness_data.head()
Homelessness_data.tail(10)

,Unnamed: 0,region,state,individuals,family_members,state_pop
41,41,West North Central,South Dakota,836.0,323.0,878698
42,42,East South Central,Tennessee,6139.0,1744.0,6771631
43,43,West South Central,Texas,19199.0,6111.0,28628666
44,44,Mountain,Utah,1904.0,972.0,3153550
45,45,New England,Vermont,780.0,511.0,624358
46,46,South Atlantic,Virginia,3928.0,2047.0,8501286
47,47,Pacific,Washington,16424.0,5880.0,7523869
48,48,South Atlantic,West Virginia,1021.0,222.0,1804291
49,49,East North Central,Wisconsin,2740.0,2167.0,5807406
50,50,Mountain,Wyoming,434.0,205.0,577601

In [18]:
""""Feature Engineering"""
New_homelessness_data = Homelessness_data[["region", "state", "individuals", "family_members", "state_pop"]]
New_homelessness_data.head()

               region       state  individuals  family_members  state_pop
0  East South Central     Alabama       2570.0           864.0    4887681
1             Pacific      Alaska       1434.0           582.0     735139
2            Mountain     Arizona       7259.0          2606.0    7158024
3  West South Central    Arkansas       2280.0           432.0    3009733
4             Pacific  California     109008.0         20964.0   39461588

In [22]:
"""Adding a New column"""
New_homelessness_data["All_Population"] = New_homelessness_data["individuals"] + New_homelessness_data["state_pop"]
New_homelessness_data.head(10)

,region,state,individuals,family_members,state_pop,All_Population
0,East South Central,Alabama,2570.0,864.0,4887681,4890251.0
1,Pacific,Alaska,1434.0,582.0,735139,736573.0
2,Mountain,Arizona,7259.0,2606.0,7158024,7165283.0
3,West South Central,Arkansas,2280.0,432.0,3009733,3012013.0
4,Pacific,California,109008.0,20964.0,39461588,39570596.0
5,Mountain,Colorado,7607.0,3250.0,5691287,5698894.0
6,New England,Connecticut,2280.0,1696.0,3571520,3573800.0
7,South Atlantic,Delaware,708.0,374.0,965479,966187.0
8,South Atlantic,District of Columbia,3770.0,3134.0,701547,705317.0
9,South Atlantic,Florida,21443.0,9587.0,21244317,21265760.0

In [17]:
""""Sorting"""
sorted_homelessness_data = Homelessness_data.sort_values(
    by= ["region"],
    ascending= True
)
sorted_homelessness_data.head(10)

,Unnamed: 0,region,state,individuals,family_members,state_pop
35,35,East North Central,Ohio,6929.0,3320.0,11676341
49,49,East North Central,Wisconsin,2740.0,2167.0,5807406
22,22,East North Central,Michigan,5209.0,3142.0,9984072
13,13,East North Central,Illinois,6752.0,3891.0,12723071
14,14,East North Central,Indiana,3776.0,1482.0,6695497
0,0,East South Central,Alabama,2570.0,864.0,4887681
42,42,East South Central,Tennessee,6139.0,1744.0,6771631
24,24,East South Central,Mississippi,1024.0,328.0,2981020
17,17,East South Central,Kentucky,2735.0,953.0,4461153
38,38,Mid-Atlantic,Pennsylvania,8163.0,5349.0,12800922

In [19]:
sorted_homelessness_data_multi_col = New_homelessness_data.sort_values(
    by= ["region", "individuals"],
    ascending= [True, True]
)
sorted_homelessness_data_multi_col.head(10)

                region        state  individuals  family_members  state_pop
49  East North Central    Wisconsin       2740.0          2167.0    5807406
14  East North Central      Indiana       3776.0          1482.0    6695497
22  East North Central     Michigan       5209.0          3142.0    9984072
13  East North Central     Illinois       6752.0          3891.0   12723071
35  East North Central         Ohio       6929.0          3320.0   11676341
24  East South Central  Mississippi       1024.0           328.0    2981020
0   East South Central      Alabama       2570.0           864.0    4887681
17  East South Central     Kentucky       2735.0           953.0    4461153
42  East South Central    Tennessee       6139.0          1744.0    6771631
30        Mid-Atlantic   New Jersey       6048.0          3350.0    8886025

In [24]:
""""Selecting Rows"""
mask = New_homelessness_data["region"] == "Mid-Atlantic"
New_homelessness_data_Mid_Atlantic = New_homelessness_data[mask]
New_homelessness_data_Mid_Atlantic

,region,state,individuals,family_members,state_pop,All_Population
30,Mid-Atlantic,New Jersey,6048.0,3350.0,8886025,8892073.0
32,Mid-Atlantic,New York,39827.0,52070.0,19530351,19570178.0
38,Mid-Atlantic,Pennsylvania,8163.0,5349.0,12800922,12809085.0

In [25]:
mask_2 = New_homelessness_data["region"] == "Mountain"
New_homelessness_data_Mountain = New_homelessness_data[mask_2]
New_homelessness_data_Mountain

,region,state,individuals,family_members,state_pop,All_Population
2,Mountain,Arizona,7259.0,2606.0,7158024,7165283.0
5,Mountain,Colorado,7607.0,3250.0,5691287,5698894.0
12,Mountain,Idaho,1297.0,715.0,1750536,1751833.0
26,Mountain,Montana,983.0,422.0,1060665,1061648.0
28,Mountain,Nevada,7058.0,486.0,3027341,3034399.0
31,Mountain,New Mexico,1949.0,602.0,2092741,2094690.0
44,Mountain,Utah,1904.0,972.0,3153550,3155454.0
50,Mountain,Wyoming,434.0,205.0,577601,578035.0

In [26]:
mask_3 = New_homelessness_data["individuals"] > 10000
New_homelessness_data_less_10k = New_homelessness_data[mask_3]
New_homelessness_data_less_10k

,region,state,individuals,family_members,state_pop,All_Population
4,Pacific,California,109008.0,20964.0,39461588,39570596.0
9,South Atlantic,Florida,21443.0,9587.0,21244317,21265760.0
32,Mid-Atlantic,New York,39827.0,52070.0,19530351,19570178.0
37,Pacific,Oregon,11139.0,3337.0,4181886,4193025.0
43,West South Central,Texas,19199.0,6111.0,28628666,28647865.0
47,Pacific,Washington,16424.0,5880.0,7523869,7540293.0

In [29]:
New_homelessness_data_less_10k_family = New_homelessness_data[New_homelessness_data["family_members"] < 10000]
New_homelessness_data_less_10k_family.head(10)
sorted_new_homelessness_data_less_10k_family = New_homelessness_data_less_10k_family.sort_values(
    by= ["family_members"],
    ascending= [True]
)
sorted_new_homelessness_data_less_10k_family

,region,state,individuals,family_members,state_pop,All_Population
34,West North Central,North Dakota,467.0,75.0,758080,758547.0
50,Mountain,Wyoming,434.0,205.0,577601,578035.0
48,South Atlantic,West Virginia,1021.0,222.0,1804291,1805312.0
41,West North Central,South Dakota,836.0,323.0,878698,879534.0
24,East South Central,Mississippi,1024.0,328.0,2981020,2982044.0
39,New England,Rhode Island,747.0,354.0,1058287,1059034.0
7,South Atlantic,Delaware,708.0,374.0,965479,966187.0
26,Mountain,Montana,983.0,422.0,1060665,1061648.0
3,West South Central,Arkansas,2280.0,432.0,3009733,3012013.0
28,Mountain,Nevada,7058.0,486.0,3027341,3034399.0
45,New England,Vermont,780.0,511.0,624358,625138.0
18,West South Central,Louisiana,2540.0,519.0,4659690,4662230.0
1,Pacific,Alaska,1434.0,582.0,735139,736573.0
31,Mountain,New Mexico,1949.0,602.0,2092741,2094690.0
29,New England,New Hampshire,835.0,615.0,1353465,1354300.0
27,West North Central,Nebraska,1745.0,676.0,1925614,1927359.0
12,Mountain,Idaho,1297.0,715.0,1750536,1751833.0
16,West North Central,Kansas,1443.0,773.0,2911359,2912802.0
40,South Atlantic,South Carolina,3082.0,851.0,5084156,5087238.0
0,East South Central,Alabama,2570.0,864.0,4887681,4890251.0
17,East South Central,Kentucky,2735.0,953.0,4461153,4463888.0
44,Mountain,Utah,1904.0,972.0,3153550,3155454.0
15,West North Central,Iowa,1711.0,1038.0,3148618,3150329.0
36,West South Central,Oklahoma,2823.0,1048.0,3940235,3943058.0
19,New England,Maine,1450.0,1066.0,1339057,1340507.0
14,East North Central,Indiana,3776.0,1482.0,6695497,6699273.0
6,New England,Connecticut,2280.0,1696.0,3571520,3573800.0
42,East South Central,Tennessee,6139.0,1744.0,6771631,6777770.0
46,South Atlantic,Virginia,3928.0,2047.0,8501286,8505214.0
25,West North Central,Missouri,3776.0,2107.0,6121623,6125399.0
49,East North Central,Wisconsin,2740.0,2167.0,5807406,5810146.0
20,South Atlantic,Maryland,4914.0,2230.0,6035802,6040716.0
11,Pacific,Hawaii,4131.0,2399.0,1420593,1424724.0
10,South Atlantic,Georgia,6943.0,2556.0,10511131,10518074.0
2,Mountain,Arizona,7259.0,2606.0,7158024,7165283.0
33,South Atlantic,North Carolina,6451.0,2817.0,10381615,10388066.0
8,South Atlantic,District of Columbia,3770.0,3134.0,701547,705317.0
22,East North Central,Michigan,5209.0,3142.0,9984072,9989281.0
5,Mountain,Colorado,7607.0,3250.0,5691287,5698894.0
23,West North Central,Minnesota,3993.0,3250.0,5606249,5610242.0
35,East North Central,Ohio,6929.0,3320.0,11676341,11683270.0
37,Pacific,Oregon,11139.0,3337.0,4181886,4193025.0
30,Mid-Atlantic,New Jersey,6048.0,3350.0,8886025,8892073.0
13,East North Central,Illinois,6752.0,3891.0,12723071,12729823.0
38,Mid-Atlantic,Pennsylvania,8163.0,5349.0,12800922,12809085.0
47,Pacific,Washington,16424.0,5880.0,7523869,7540293.0
43,West South Central,Texas,19199.0,6111.0,28628666,28647865.0
9,South Atlantic,Florida,21443.0,9587.0,21244317,21265760.0

In [30]:
"""Query"""
New_homelessness_data_sorted = New_homelessness_data.query(
    "region == 'Pacific' and individuals > 10000"
)
New_homelessness_data_sorted

,region,state,individuals,family_members,state_pop,All_Population
4,Pacific,California,109008.0,20964.0,39461588,39570596.0
37,Pacific,Oregon,11139.0,3337.0,4181886,4193025.0
47,Pacific,Washington,16424.0,5880.0,7523869,7540293.0

In [31]:
New_homelessness_data_sorted2 = New_homelessness_data.query(
    "region == 'Mountain' and individuals < 10000"
)
New_homelessness_data_sorted2

,region,state,individuals,family_members,state_pop,All_Population
2,Mountain,Arizona,7259.0,2606.0,7158024,7165283.0
5,Mountain,Colorado,7607.0,3250.0,5691287,5698894.0
12,Mountain,Idaho,1297.0,715.0,1750536,1751833.0
26,Mountain,Montana,983.0,422.0,1060665,1061648.0
28,Mountain,Nevada,7058.0,486.0,3027341,3034399.0
31,Mountain,New Mexico,1949.0,602.0,2092741,2094690.0
44,Mountain,Utah,1904.0,972.0,3153550,3155454.0
50,Mountain,Wyoming,434.0,205.0,577601,578035.0